///////////////////////////////////////////////
//THIS FILE WAS GENERATED BY THE PREPROCESSOR
//DO NOT EDIT THIS FILE DIRECTLY
///////////////////////////////////////////////




FO_fn_getUnlockedItems = {
	private _unlockedItems  = [];
	private _baseUnlocks  = [
		["rhs_weap_l1a1_wood",  1,  1, "rhs_mag_20Rnd_762x51_m80_fnfal"],
		["rhsusf_weap_MP7A2",   1,  1, "rhsusf_mag_40Rnd_46x30_FMJ"],
		["V_PlateCarrier1_rgr", 1,  1, ""]
	];

	_unlockedItems append _baseUnlocks;
	_unlockedItems;
};
