///////////////////////////////////////////////
//THIS FILE WAS GENERATED BY THE PREPROCESSOR
//DO NOT EDIT THIS FILE DIRECTLY
///////////////////////////////////////////////




FO_fn_getUnlockedItems = {
	private _unlockedItems  = [];
	private _baseUnlocks  = [
		["rhs_weap_savz61_folded",  1,  1, "rhsgref_20rnd_765x17_vz61"],
		["rhs_weap_kar98k",   1,  1, "rhsgref_5Rnd_792x57_kar98k"],
		["U_BG_Guerrilla_6_1", 1, 1, ""],
		["V_I_G_resistanceLeader_F", 1, 1, ""]
	];

	_unlockedItems append _baseUnlocks;
	_unlockedItems;
};
